services:
  api:
    image: simpla-backend:${TAG:-dev}
    build: &api-build
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PYTHONPATH: /app
    networks:
      - app-net

  frontend:
    image: simpla-frontend:${TAG:-dev}
    build: &front-build
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: ${PUBLIC_API_URL}
    networks:
      - app-net

networks:
  app-net:
