version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: simpla
      POSTGRES_USER: simpla
      POSTGRES_PASSWORD: simpla
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/simpla
      SPRING_DATASOURCE_USERNAME: simpla
      SPRING_DATASOURCE_PASSWORD: simpla
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data: 