# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/proto/relational.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ore/proto/relational.proto\x12\nrelational\"\x1c\n\x0cStoreRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"J\n\rStoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0fpk_mapping_json\x18\x03 \x01(\t\",\n\x16ReconstructNormRequest\x12\x12\n\ninfoleg_id\x18\x01 \x01(\x05\"(\n\x1aReconstructNormByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"O\n\x17ReconstructNormResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nnorma_json\x18\x03 \x01(\t\"&\n\nEntityPair\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x03\";\n\x0fGetBatchRequest\x12(\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x16.relational.EntityPair\"I\n\x10GetBatchResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bnormas_json\x18\x03 \x01(\t2\xd8\x02\n\x11RelationalService\x12<\n\x05Store\x12\x18.relational.StoreRequest\x1a\x19.relational.StoreResponse\x12Z\n\x0fReconstructNorm\x12\".relational.ReconstructNormRequest\x1a#.relational.ReconstructNormResponse\x12\x62\n\x13ReconstructNormById\x12&.relational.ReconstructNormByIdRequest\x1a#.relational.ReconstructNormResponse\x12\x45\n\x08GetBatch\x12\x1b.relational.GetBatchRequest\x1a\x1c.relational.GetBatchResponseB0\n\x1b\x63om.simpla.relational.protoB\x0fRelationalProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.proto.relational_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.simpla.relational.protoB\017RelationalProtoP\001'
  _globals['_STOREREQUEST']._serialized_start=43
  _globals['_STOREREQUEST']._serialized_end=71
  _globals['_STORERESPONSE']._serialized_start=73
  _globals['_STORERESPONSE']._serialized_end=147
  _globals['_RECONSTRUCTNORMREQUEST']._serialized_start=149
  _globals['_RECONSTRUCTNORMREQUEST']._serialized_end=193
  _globals['_RECONSTRUCTNORMBYIDREQUEST']._serialized_start=195
  _globals['_RECONSTRUCTNORMBYIDREQUEST']._serialized_end=235
  _globals['_RECONSTRUCTNORMRESPONSE']._serialized_start=237
  _globals['_RECONSTRUCTNORMRESPONSE']._serialized_end=316
  _globals['_ENTITYPAIR']._serialized_start=318
  _globals['_ENTITYPAIR']._serialized_end=356
  _globals['_GETBATCHREQUEST']._serialized_start=358
  _globals['_GETBATCHREQUEST']._serialized_end=417
  _globals['_GETBATCHRESPONSE']._serialized_start=419
  _globals['_GETBATCHRESPONSE']._serialized_end=492
  _globals['_RELATIONALSERVICE']._serialized_start=495
  _globals['_RELATIONALSERVICE']._serialized_end=839
# @@protoc_insertion_point(module_scope)
