# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vectorial.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvectorial.proto\x12\tvectorial\"\x1c\n\x0cStoreRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"1\n\rStoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x99\x01\n\rSearchRequest\x12\x11\n\tembedding\x18\x01 \x03(\x01\x12\x36\n\x07\x66ilters\x18\x02 \x03(\x0b\x32%.vectorial.SearchRequest.FiltersEntry\x12\r\n\x05limit\x18\x03 \x01(\x05\x1a.\n\x0c\x46iltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9c\x01\n\x0cSearchResult\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x37\n\x08metadata\x18\x03 \x03(\x0b\x32%.vectorial.SearchResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\\\n\x0eSearchResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12(\n\x07results\x18\x03 \x03(\x0b\x32\x17.vectorial.SearchResult2\x8d\x01\n\x10VectorialService\x12:\n\x05Store\x12\x17.vectorial.StoreRequest\x1a\x18.vectorial.StoreResponse\x12=\n\x06Search\x12\x18.vectorial.SearchRequest\x1a\x19.vectorial.SearchResponseB.\n\x1a\x63om.simpla.vectorial.protoB\x0eVectorialProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectorial_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.simpla.vectorial.protoB\016VectorialProtoP\001'
  _globals['_SEARCHREQUEST_FILTERSENTRY']._options = None
  _globals['_SEARCHREQUEST_FILTERSENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHRESULT_METADATAENTRY']._options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_STOREREQUEST']._serialized_start=30
  _globals['_STOREREQUEST']._serialized_end=58
  _globals['_STORERESPONSE']._serialized_start=60
  _globals['_STORERESPONSE']._serialized_end=109
  _globals['_SEARCHREQUEST']._serialized_start=112
  _globals['_SEARCHREQUEST']._serialized_end=265
  _globals['_SEARCHREQUEST_FILTERSENTRY']._serialized_start=219
  _globals['_SEARCHREQUEST_FILTERSENTRY']._serialized_end=265
  _globals['_SEARCHRESULT']._serialized_start=268
  _globals['_SEARCHRESULT']._serialized_end=424
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_start=377
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_end=424
  _globals['_SEARCHRESPONSE']._serialized_start=426
  _globals['_SEARCHRESPONSE']._serialized_end=518
  _globals['_VECTORIALSERVICE']._serialized_start=521
  _globals['_VECTORIALSERVICE']._serialized_end=662
# @@protoc_insertion_point(module_scope)
