name: Mirror GitHub → Bitbucket

on:
  push:
    branches:
      - '**' # triggers on any branch push

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone full GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all branches and tags

      - name: Mirror to Bitbucket
        run: |
          git config --global user.email "ci@yourdomain.com"
          git config --global user.name "GitHub Actions Bot"

          # Add Bitbucket remote (using HTTPS with app password)
          git remote add bitbucket https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/${{ secrets.BITBUCKET_REPO }}.git

          # Fetch all branches from Bitbucket first
          git fetch bitbucket

          # For each branch on the GitHub remote (origin), merge Bitbucket changes and push
          for branch in $(git branch -r | grep 'origin/' | grep -v 'origin/HEAD' | sed 's@origin/@@'); do
            echo "Processing branch: $branch"
            
            # Checkout the branch from origin
            git checkout -B "$branch" "origin/$branch"
            
            # Try to merge Bitbucket changes (if they exist)
            if git show-ref --verify --quiet "refs/remotes/bitbucket/$branch"; then
              echo "Merging Bitbucket changes for $branch"
              git merge "bitbucket/$branch" --no-edit || echo "Merge conflict in $branch, using GitHub version"
            fi
            
            # Push to Bitbucket
            git push bitbucket "$branch:$branch" --force
          done
          
          # Push all tags
          git push --tags bitbucket
