name: Mirror GitHub → Bitbucket

on:
  push:
    branches:
      - '**' # triggers on any branch push

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Clone full GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all branches and tags

      - name: Mirror to Bitbucket
        run: |
          git config --global user.email "ci@yourdomain.com"
          git config --global user.name "GitHub Actions Bot"

          # Add Bitbucket remote (using HTTPS with app password)
          git remote add bitbucket https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/${{ secrets.BITBUCKET_REPO }}.git

          # Push all branches, tags, remotes — full sync
          # First, push all branches and tags
          git push --all bitbucket
          git push --tags bitbucket
          
          # Handle the main branch separately to avoid deletion issues
          # Check if main branch exists and push it
          if git show-ref --verify --quiet refs/heads/main; then
            git push --force bitbucket main:main
          elif git show-ref --verify --quiet refs/remotes/origin/main; then
            git push --force bitbucket origin/main:main
          else
            echo "No main branch found, skipping main branch push"
          fi
